In [2]:
from scipy import stats
import numpy as np
from random import randint

In [4]:
my_list=[randint(-10,10) for x in range(20)]
my_list

[1, 2, 5, -7, 4, 6, 7, -9, 8, 7, -6, 8, -7, -3, 0, 2, -3, -5, 1, -8]

In [5]:
np_list = np.asarray(my_list)
np_list

array([ 1,  2,  5, -7,  4,  6,  7, -9,  8,  7, -6,  8, -7, -3,  0,  2, -3,
       -5,  1, -8])

## mean

In [6]:
np.mean(np_list)

0.15

## median

In [7]:
np.median(np_list)

1.0

## mode

In [14]:
stats.mode(np_list)

ModeResult(mode=array([-7]), count=array([2]))

In [17]:
my_list2=[randint(-10,10) for x in range (100)]
np_list2 = np.asarray(my_list2)
np_list2

array([  8,  10,   0,  -9,   6,  -6, -10,   5,  -5,   9,  -6,  -7,  -1,
        -3,   1,   4,   2,  -6,  -5,   1,  -3,  -9,   1,   3,  -3,  -9,
         9,   6,  -9,  10,  -8,   8,  -9,   9,   5,   0,  -1,  -6,  -4,
        -7,   7,  -5,  -3,  -1,   5,   1,   2,   6,   7,   0,  -5,   4,
        -5,  -1,   6,   9,   7,  10,  -7,  -4,  10,   1,   9,  -9,  10,
         6,  -8,   3,  -1,   6,   1,   3,  -3,   3,  -7,   2,  -3,   8,
        10,   9,  -6,   0,  -8,   3,   1,  10,  -1,   9,  -6,   6,   0,
        -6,  -2,  10, -10,  -7,   2,  -4,  -5,   1])

## variance

In [19]:
np.var(np_list2)

37.5419

## standard deviation

In [21]:
np.std(np_list2)

6.1271445225324985

##################################

In [3]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
np.arange(30).reshape(5,6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [6]:
np1 = np.array([1,2,3,4])
np2 = np.array([[1,2,3,4],[5,6,7,8]])
np3 = np.array([[[1,2,3,4],[5,6,7,8]],[[9,10,11,12],[13,14,15,16]]])
print('np1')
print(np1)
print('np2')
print(np2)
print('np3')
print(np3)

np1
[1 2 3 4]
np2
[[1 2 3 4]
 [5 6 7 8]]
np3
[[[ 1  2  3  4]
  [ 5  6  7  8]]

 [[ 9 10 11 12]
  [13 14 15 16]]]


In [7]:
np3.ndim

3

In [8]:
np3.shape

(2, 2, 4)

In [9]:
np3.size

16

In [10]:
np3.dtype

dtype('int64')

In [11]:
np.arange(3,30,3)

array([ 3,  6,  9, 12, 15, 18, 21, 24, 27])

In [15]:
np.zeros((4,3,2))

array([[[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]]])

In [16]:
np.zeros((2,3,4))

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [17]:
np.ones((4,3,2))

array([[[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]]])

In [19]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [20]:
np.full((3,4),7)

array([[7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7]])

In [21]:
np.diag((3,5,8,2,9))

array([[3, 0, 0, 0, 0],
       [0, 5, 0, 0, 0],
       [0, 0, 8, 0, 0],
       [0, 0, 0, 2, 0],
       [0, 0, 0, 0, 9]])

In [23]:
c = np.arange(30).reshape(5,6)
c

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [24]:
d = np.insert(c,1,np.arange(80,85),axis=1)
d

array([[ 0, 80,  1,  2,  3,  4,  5],
       [ 6, 81,  7,  8,  9, 10, 11],
       [12, 82, 13, 14, 15, 16, 17],
       [18, 83, 19, 20, 21, 22, 23],
       [24, 84, 25, 26, 27, 28, 29]])

In [25]:
e = np.insert(c,3,np.arange(71,77),axis=0)
e

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [71, 72, 73, 74, 75, 76],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [26]:
coba = np.arange(15).reshape(3,5)
coba

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [30]:
t = np.zeros((1,coba.shape[1]))
t

array([[0., 0., 0., 0., 0.]])

In [31]:
for i in np.arange(coba.shape[0]):
    t = np.insert(t,i+1,coba[i:i+1],axis=0)
t

array([[ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  1.,  2.,  3.,  4.],
       [ 5.,  6.,  7.,  8.,  9.],
       [10., 11., 12., 13., 14.]])

In [32]:
f = np.delete(t,0,axis=0)
f

array([[ 0.,  1.,  2.,  3.,  4.],
       [ 5.,  6.,  7.,  8.,  9.],
       [10., 11., 12., 13., 14.]])

In [33]:
v = np.array([1,2,3])

In [34]:
np.tile(v,(3,2))

array([[1, 2, 3, 1, 2, 3],
       [1, 2, 3, 1, 2, 3],
       [1, 2, 3, 1, 2, 3]])

In [37]:
np.random.random()

0.8123969633471251

In [38]:
np.random.random((3,5))

array([[0.74547186, 0.51106808, 0.47796617, 0.36894069, 0.31358622],
       [0.37025695, 0.07968786, 0.56495897, 0.46528583, 0.3805649 ],
       [0.34390659, 0.90950705, 0.86591971, 0.34499623, 0.39874598]])

In [47]:
y = np.linspace(0,1,101)
y

array([0.  , 0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ,
       0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 , 0.21,
       0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 , 0.31, 0.32,
       0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 , 0.41, 0.42, 0.43,
       0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 , 0.51, 0.52, 0.53, 0.54,
       0.55, 0.56, 0.57, 0.58, 0.59, 0.6 , 0.61, 0.62, 0.63, 0.64, 0.65,
       0.66, 0.67, 0.68, 0.69, 0.7 , 0.71, 0.72, 0.73, 0.74, 0.75, 0.76,
       0.77, 0.78, 0.79, 0.8 , 0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87,
       0.88, 0.89, 0.9 , 0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98,
       0.99, 1.  ])

In [48]:
y.itemsize

8

In [50]:
np.arange(24).reshape(4,3,-1)

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]],

       [[12, 13],
        [14, 15],
        [16, 17]],

       [[18, 19],
        [20, 21],
        [22, 23]]])

In [51]:
n = np.arange(2,20,2)
n

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [52]:
n[[1,2,3]]

array([4, 6, 8])

In [53]:
n[4]

10

In [54]:
n[2:]

array([ 6,  8, 10, 12, 14, 16, 18])

In [56]:
n[:3]

array([2, 4, 6])

In [59]:
n[-2:]

array([16, 18])

In [60]:
n[:-2]

array([ 2,  4,  6,  8, 10, 12, 14])

In [61]:
n[2:5]

array([ 6,  8, 10])

In [70]:
xx = np.arange(24).reshape(6,4)
xx

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [63]:
xx[5,3]

23

In [65]:
xx[2,0]

8

In [66]:
xx > 17

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False,  True,  True],
       [ True,  True,  True,  True]])

In [67]:
xx[(xx>7) & (xx<19)]

array([ 8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18])

In [80]:
xx[2:4]

array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [81]:
kk = np.arange(10)
qq=kk
np.shares_memory(qq,kk)

True

In [82]:
w = np.arange(30)
o = w.copy()
np.shares_memory(w,o)

False

In [83]:
ee = np.array([[1,2,3],[4,5,6]])
ee

array([[1, 2, 3],
       [4, 5, 6]])

In [85]:
#transpose
ee.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [86]:
dc = np.array([1,2,3,4])
cd = np.array([1,2,3,5])
dc == cd

array([ True,  True,  True, False])

In [88]:
np.vstack((cd,dc))

array([[1, 2, 3, 5],
       [1, 2, 3, 4]])

In [89]:
np.hstack((cd,dc))

array([1, 2, 3, 5, 1, 2, 3, 4])

In [90]:
ff = np.arange(10)
np.sin(ff)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [91]:
np.sum(ff)

45

In [92]:
np.cos(ff)

array([ 1.        ,  0.54030231, -0.41614684, -0.9899925 , -0.65364362,
        0.28366219,  0.96017029,  0.75390225, -0.14550003, -0.91113026])

In [93]:
np.exp(ff)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [110]:
nb = np.arange(1,10).reshape(3,3)
nb

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [111]:
#determinan
np.linalg.det(nb)

0.0

In [112]:
#eigen value
np.linalg.eig(nb)

(array([ 1.61168440e+01, -1.11684397e+00, -1.30367773e-15]),
 array([[-0.23197069, -0.78583024,  0.40824829],
        [-0.52532209, -0.08675134, -0.81649658],
        [-0.8186735 ,  0.61232756,  0.40824829]]))

In [113]:
cx = nb.T
cx

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [114]:
#dot product
np.dot(cx,nb)

array([[ 66,  78,  90],
       [ 78,  93, 108],
       [ 90, 108, 126]])

In [115]:
hh = np.array([[1,2],[3,4]])
hh

array([[1, 2],
       [3, 4]])

In [116]:
hh.sum(axis = 1)

array([3, 7])

In [117]:
hh.sum(axis = 0)

array([4, 6])